---
title: "BeerAdvocate Data Exploration"
author: "Jakob Johnson"
date: "10/10/2018"
output: 
html_document:
css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath(".."))
library(data.table)
library(ggplot2)
library(dplyr)
```

## Import Data

In this exploration we will be using `ggplot2`, `dplyr`, and `data.table` to read in the data.

```{r import1, warning=FALSE}
t1 <- fread("data/beer_reviews-1.csv")
t2 <- fread("data/beer_reviews-2.csv")
t3 <- fread("data/beer_reviews-3.csv")
t4 <- fread("data/beer_reviews-4.csv")
  
ba_raw <- rbind(t1, t2, t3, t4) %>% as_tibble() %>% select(-V1)# import the data as a dplyr tibble
rm(t1, t2, t3, t4)
colnames(ba_raw) # the variables:
```

Let's get rid of some of those extra variables that we don't care about

```{r import2}
ba <- select(ba_raw, -c(brewery_id, review_time, review_profilename, beer_beerid))
knitr::kable(head(ba))
```

These data represent `r length(ba$review_overall)` different reviews of `r length(unique(ba$beer_name))` beers from `r length(unique(ba$brewery_name))` different breweries. 

## Plots

```{r plots1, fig.align="center", warning=FALSE}
p1 <- ggplot(ba) +
  stat_bin(aes(x = review_overall), binwidth = 0.25, fill = "#d1730c")
p1
```

```{r breweries}

brew <- unique(ba$brewery_name)

beer <- unique(ba$beer_name)

style <- unique(ba$beer_style)

```

```{r plots2}

overTime <- tibble(time = c(8, 9, 10, 11, 12,
                            8, 9, 10, 11, 12,
                            8, 9, 10, 11, 12,
                            8, 9, 10, 11, 12,
                            8, 9, 10, 11, 12,
                            8, 9, 10, 11, 12), 
                   ave_rating = c(3.9, 3.8, 3.6, 4.7, 3.4, 
                                  4.0, 3.7, 3.5, 3.6, 3.3, 
                                  4.0, 3.7, 3.5, 3.6, 3.3,
                                  3.5, 3.6, 3.4, 3.5, 3.5, 
                                  3.8, 3.9, 3.8, 3.7, 4.0, 
                                  3.8, 3.9, 3.8, 3.7, 4.0),
                   person = c(1,1,1,1,1,
                              2,2,2,2,2,
                              3,3,3,3,3,
                              4,4,4,4,4,
                              5,5,5,5,5,
                              6,6,6,6,6),
                   abv = c('high','high','high','high','high',
                           'high','high','high','high','high',
                           'high','high','high','high','high',
                           'low','low','low','low','low',
                           'low','low','low','low','low',
                           'low','low','low','low','low'))

time_plot <- ggplot(overTime, aes(x = time, y = ave_rating, color = abv)) + 
  geom_smooth() + labs(title = "Average Rating over a night") + theme_bw()
time_plot

ggsave("process_img/time_vis.jpg", time_plot, width = 6, height = 4, units = 'in')

```